[template]
src  = "nginx.conf.tmpl"
dest = "/usr/local/openresty/nginx/conf/nginx.conf"
keys = [
    "/client/id",
    "/client/secret",
    "/fqdn",
    "/keycloak/fqdn",
    "/keycloak/realm",
    "/maxbody",
    "/proxy",
    "/redirect",
    "/http",
    "/https",
    "/stream"
]